agent:
  name: pyannote_diarizer
templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}
- template_name: SinapsisPyannoteDiarizer
  class_name: SinapsisPyannoteDiarizer
  template_input: InputTemplate
  attributes:
    model_name: pyannote/speaker-diarization-community-1
    device: cuda
    chunk_size_in_secs: -1
    audio_file_path: <<path to audio>>
    num_speakers: 2
