fail_fast: True

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: "docs/.*"
      - id: trailing-whitespace
        exclude: "docs/.*"
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: "docs/.*"
      - id: check-added-large-files
        args: ["--maxkb=20"]
      - id: check-docstring-first
        exclude: "docs/.*"
      - id: check-case-conflict
        exclude: "docs/.*"
      - id: check-shebang-scripts-are-executable
        exclude: "docs/.*"
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        exclude: ".*/tests/.*"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --explicit-package-bases
        language: python
        types: [python]
        additional_dependencies:
          - "pydantic>=2.8.2"
